# CPM Package Configuration

[project]
name = "countries-api"
version = "0.1.0"
description = "REST API for countries - uWebSockets + nlohmann/json"
cpp_standard = "20"
entry = "main.cpp"
output = "countries-api"

[scripts]
start = "./countries-api"

[dependencies]
json = "github:nlohmann/json"
uWebSockets = "github:uNetworking/uWebSockets@v20.64.0"

[system-dependencies]
uSockets = "github:uNetworking/uSockets@v0.8.8"
