[project]
name = "myapp"
version = "0.1.0"
cpp_standard = "20"
entry = "main.cpp"
output = "myapp"

[scripts]
start = "./myapp"

[dependencies]

[system-dependencies]
seastar = "github:scylladb/seastar"
