# CPM Package Configuration

[project]
name = "countries-api"
version = "0.1.0"
description = "REST API for countries - Seastar + nlohmann/json"
cpp_standard = "23"
entry = "main.cpp"
output = "countries-api"

[scripts]
start = "./countries-api --smp 1"

[dependencies]
json = "github:nlohmann/json"

[system-dependencies]
seastar = "github:scylladb/seastar"
